SELECT
    STRIKER_PLAYER_ID AS PLAYER_ID,
    BATTING_TEAM_ID AS TEAM_ID,

    COUNT(*) AS BALLS_FACED,

    SUM(BATSMAN_RUNS) AS RUNS,

    SUM(IS_FOUR) AS FOURS,

    SUM(IS_SIX) AS SIXES,

    SUM(IS_DOT_BALL) AS DOT_BALLS,

    COUNT(DISTINCT MATCH_ID) AS MATCHES_PLAYED

FROM {{ ref('stg_cricket_deliveries') }}

GROUP BY
    STRIKER_PLAYER_ID,
    BATTING_TEAM_ID