SELECT
    BOWLER_PLAYER_ID AS PLAYER_ID,
    BOWLING_TEAM_ID AS TEAM_ID,

    COUNT(*) AS BALLS_BOWLED,

    SUM(
        CASE
            WHEN WIDES = 0 AND NO_BALLS = 0 THEN 1
            ELSE 0
        END
    ) AS LEGAL_BALLS,

    SUM(BATSMAN_RUNS + WIDES + NO_BALLS) AS RUNS_CONCEDED,

    SUM(WIDES) AS WIDES,

    SUM(NO_BALLS) AS NO_BALLS,

    SUM(IS_WICKET) AS WICKETS,

    COUNT(DISTINCT MATCH_ID) AS MATCHES_PLAYED

FROM {{ ref('stg_cricket_deliveries') }}

GROUP BY
    BOWLER_PLAYER_ID,
    BOWLING_TEAM_ID