WITH batting AS (
    SELECT
        PLAYER_ID,
        SUM(BALLS_FACED) AS BALLS_FACED,
        SUM(RUNS) AS RUNS,
        SUM(FOURS) AS FOURS,
        SUM(SIXES) AS SIXES,
        SUM(DOT_BALLS) AS DOT_BALLS,
        SUM(MATCHES_PLAYED) AS MATCHES_PLAYED
    FROM {{ ref('batting_analytics') }}
    GROUP BY PLAYER_ID
),

bowling AS (
    SELECT
        PLAYER_ID,
        SUM(BALLS_BOWLED) AS BALLS_BOWLED,
        SUM(LEGAL_BALLS) AS LEGAL_BALLS,
        SUM(RUNS_CONCEDED) AS RUNS_CONCEDED,
        SUM(WIDES) AS WIDES,
        SUM(NO_BALLS) AS NO_BALLS,
        SUM(WICKETS) AS WICKETS,
        SUM(MATCHES_PLAYED) AS MATCHES_PLAYED
    FROM {{ ref('bowling_analytics') }}
    GROUP BY PLAYER_ID
)

SELECT
    p.PLAYER_ID,
    p.FIRST_NAME,
    p.LAST_NAME,
    p.NATIONALITY,
    p.BATTING_STYLE,
    p.BOWLING_STYLE,
    p.ROLE,
    p.CURRENT_TEAM_ID,
    p.CONTRACT_START,
    p.STATUS,

    COALESCE(b.BALLS_FACED, 0) AS BALLS_FACED,
    COALESCE(b.RUNS, 0) AS TOTAL_RUNS,
    COALESCE(b.FOURS, 0) AS FOURS,
    COALESCE(b.SIXES, 0) AS SIXES,
    COALESCE(b.DOT_BALLS, 0) AS BATTING_DOT_BALLS,
    COALESCE(b.MATCHES_PLAYED, 0) AS BATTING_MATCHES,

    COALESCE(w.BALLS_BOWLED, 0) AS BALLS_BOWLED,
    COALESCE(w.LEGAL_BALLS, 0) AS LEGAL_BALLS,
    COALESCE(w.RUNS_CONCEDED, 0) AS RUNS_CONCEDED,
    COALESCE(w.WIDES, 0) AS WIDES,
    COALESCE(w.NO_BALLS, 0) AS NO_BALLS,
    COALESCE(w.WICKETS, 0) AS WICKETS,
    COALESCE(w.MATCHES_PLAYED, 0) AS BOWLING_MATCHES,

    p.UPDATED_AT

FROM {{ ref('stg_cricket_players') }} p

LEFT JOIN batting b
    ON p.PLAYER_ID = b.PLAYER_ID

LEFT JOIN bowling w
    ON p.PLAYER_ID = w.PLAYER_ID
    