name: 'cricket_dbt'
version: '1.0.0'

profile: 'cricket_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["models/bronze"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  cricket_dbt:

    silver:
      +materialized: table
      +schema: SILVER

    gold:
      +materialized: table
      +schema: GOLD

      dimensions:
        +materialized: table

      facts:
        +materialized: table


seeds:
  cricket_dbt:
    +schema: BRONZE